version: '3'
services:
  app:
    build:
      .
    ports:
      - "8081:8081"
    depends_on:
      - "postgresdb"
      - 'redis'
  postgresdb:
    image: postgres
    environment:
      POSTGRES_DB: "soa-payment-service"
  redis:
    image: redis
    ports:
      - "6379:6379"